#!/bin/bash

# revdescr
rdescr="$*";
[ -z "$rdescr" ] && rdescr="$(date)"

comma=" "
cmdh=include/30-rpc-cmd.h
idsh=include/30-rpc-ids.h
echo "enum RPC_ids {" > $idsh
echo "char *RPC_cmd[] = {" > $cmdh
sort ZZZ_RPC_List.txt | while read rpc_cmd; do
	rpc_cmd=$(sed 's/ //g' <<< $rpc_cmd)
	[ -z "$rpc_cmd" ] && continue;
	echo $rpc_cmd 1>&2
	rpc_id=$(sed -e 's/[.]/_/g' -e 's/[|]//g' <<< $rpc_cmd)
	echo -e "${comma}$rpc_id" >> $idsh
	echo -e "${comma}\"$rpc_cmd\"" >> $cmdh
	comma=","
done 
echo -e "};" >> $idsh
echo -e "};" >> $cmdh

# updates to last revision
git add . -A
git commit -m "$rdescr" -a
git push

git pull
cat > include/revision.h << EOT
#define REVISION \"$(git describe --tags | tail -n 1)\"" 
#define REV_DATE \"$(git log -1 --format=%cd | tail -n 1)\"" 
EOT

dat=(git log -1 --format=%cd)

# Generates prototypes
protoh=include/00-prototypes.h
echo "#ifdef __PROTO__" > $protoh
echo "#define __PROTO__" > $protoh
echo "//Extracted Prototyes" >> $protoh
for fn in src/*c*; do
	grep -q static <<< $fn && continue
	echo "extracting prototypes from  $fn..."
	echo "// ****************************" >> $protoh
	echo "// $fn" >> $protoh
	echo "// ****************************" >> $protoh
	grep '[a-z0-9A-Z_]\+ [a-z0-9A-Z_*]\+ *([a-z0-9A-Z,*& _.]*) *{' $fn \
		| sed  -e 's/ {.*$/;/g' \
		>> $protoh
	done



echo "#endif" >> $protoh

echo "Generated Revision.h"

