#!/bin/bash

# revdescr
rdescr="$*";
[ -z "$rdescr" ] && rdescr="$(date)"

comma=" "
cmdh=include/30-rpc-cmd.h
idsh=include/30-rpc-ids.h
echo "enum RPC_ids {" > $idsh
echo "char *RPC_cmd[] = {" > $cmdh
sort ZZZ_RPC_List.txt | while read rpc_cmd; do
	rpc_cmd=$(sed 's/ //g' <<< $rpc_cmd)
	[ -z "$rpc_cmd" ] && continue;
	echo $rpc_cmd 1>&2
	rpc_id=$(sed -e 's/[.]/_/g' -e 's/[|]//g' <<< $rpc_cmd)
	echo -e "${comma}$rpc_id" >> $idsh
	echo -e "${comma}\"$rpc_cmd\"" >> $cmdh
	comma=","
done 
echo -e "};" >> $idsh
echo -e "};" >> $cmdh

# Generates prototypes
for fn in src/*.c*; do
	fh=$(sed -E -e 's/[.].*/.h/g' -e 's/.*\//include\//g' <<< $fn)
	ft="__PROTO_$(sed -E -e 's/[.-]/_/g' -e 's/.*\///g' <<< $fn | tr '[:lower:]' '[:upper:]')__"
	echo "extracting prototypes from  $fn to $fh: $ft ..." 1>&2
	echo -n > $fh
	echo "#ifndef $ft" >> $fh
	echo "#define $ft" >> $fh
	echo "//Extracted Prototyes" >> $fh
	echo "// ****************************"
	echo "// $fn prototypes" 
	echo "// ****************************"
	grep '[a-z0-9A-Z_]\+ [a-z0-9A-Z_*]\+ *([a-z0-9A-Z,*& _.]*) *{' "$fn" \
		| grep -v static \
		| sed  -e 's/ {.*$/;/g' \
		>> $fh
	echo "#endif" >> $fh
done 


# updates to last revision
git add . -A
git commit -m "$rdescr" -a
git push

cat > include/revision.h << EOT
#define REV_DATE \"$(git log -1 --format=%cd | tail -n 1)\"" 
EOT

